version: "3.9"
services:
  postgres:
    image: mirror.gcr.io/postgres
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "tech"
      POSTGRES_PASSWORD: "tech"
    ports:
      - "5432:5432"
    networks:
      - net
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: database
      KC_DB_PASSWORD: tech
      KC_DB_USERNAME: tech
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    depends_on:
      - postgres
    networks:
      - net
networks:
  net:
    driver: bridge
